name: Bug 回報
description: 回報遇到的錯誤
labels: [bug]
title: "[Bug]: "
body:
- type: textarea
id: steps
attributes:
label: 重現步驟
description: 請逐步描述如何重現問題
validations:
required: true
- type: textarea
id: expected
attributes:
label: 預期結果
- type: textarea
id: actual
attributes:
label: 實際結果（含截圖/錯誤訊息）
- type: input
id: version
attributes:
label: PocketEditor 版本
placeholder: 例如 v0.1.0
- type: input
id: os
attributes:
label: 作業系統 / 版本
placeholder: 例如 Windows 10/11 22H2
- type: textarea
id: logs
attributes:
label: 相關日誌（可選）
description: 請貼上與問題相關的 log 片段（請避免包含個資）
