name: 功能提案
description: 建議新功能或改善
labels: [enhancement]
title: "[Feature]: "
body:
- type: textarea
id: problem
attributes:
label: 想解決的問題
description: 請描述你的痛點或使用場景
- type: textarea
id: proposal
attributes:
label: 建議的解法
- type: textarea
id: alternatives
attributes:
label: 你考慮過的替代方案（若有）
- type: textarea
id: extra
attributes:
label: 其他補充
